input {
    file {
        path => "/logs/php/*"
        start_position => "beginning"
        codec => "json"
    }
    file {
        path => "/logs/java/*"
        start_position => "beginning"
        codec => "json"
    }
}

output {
    if [log][file][path] =~ "/logs/java/" {
        elasticsearch {
            index => "codelytv-java"
            hosts => ["elasticsearch:9200"]
        }
    } else {
        elasticsearch {
            index => "codelytv"
            hosts => ["elasticsearch:9200"]
        }
    }
}