input {
    file {
        path => "/logs/php/*"
        start_position => "beginning"
        codec => "json"
    }
    file {
        path => "/logs/java/*"
        start_position => "beginning"
        codec => "json"
    }
}

filter {
    translate {
        field => "[level]"
        destination => "[level]"
        dictionary => {
            "ERROR" => 200
            "error" => 200
        }
        fallback => 100
    }
}

output {
    elasticsearch {
        index => "codelytv"
        hosts => ["elasticsearch:9200"]
    }
}