FROM docker.elastic.co/logstash/logstash:8.1.0

# this is not needed, because the plugin is already included in the image
# RUN rm -f /usr/share/logstash/pipeline/logstash.conf && \
#     bin/logstash-plugin install logstash-filter-translate
